apiVersion: v1
kind: Service
metadata: 
    name: cetus-web-service
spec:
    type: NodePort
    ports:
        - port: 3009
          nodePort: 80
          protocol: TCP
          targetPort: 3009
    selector:
        app: my-page-Pod